# Ported from https://github.com/huggingface/alignment-handbook/blob/main/recipes/zephyr-7b-beta/dpo/config_lora.yaml
# with slight modifications to add `wandb` logging, Notus-related stuff. Also the fine tune is done over the SFT 
# fine-tuned model instead of over the LoRA fine-tuned model.

# Model arguments
model_name_or_path: mistralai/Mixtral-8x7B-Instruct-v0.1
torch_dtype: auto

# LoRA arguments
use_peft: true
lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments
dataset_mixer:
  argilla/ultrafeedback-binarized-preferences-cleaned: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: epoch
eval_steps: 100
gradient_accumulation_steps: 32
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: data/notux-8x7b-v1-lora
per_device_train_batch_size: 2
per_device_eval_batch_size: 4
push_to_hub: true
hub_model_id: argilla/notux-8x7b-v1-lora
hub_private_repo: true
save_strategy: epoch
save_total_limit: 1
seed: 42
warmup_ratio: 0.1
report_to:
  - wandb
  - tensorboard
