notus-7b-v1:
  prompt_template: "notus-7b-v1/prompt.txt"
  fn_completions: "huggingface_local_completions"
  completions_kwargs:
    model_name: "argilla/notus-7b-v1"
    model_kwargs:
      torch_dtype: "bfloat16"
    max_new_tokens: 2048
    temperature: 0.7
    top_p: 1.0
    do_sample: True
  pretty_name: "Notus 7B v1"
  link: "https://huggingface.co/argilla/notus-7b-v1"
