# Model arguments
model_name_or_path: alignment-handbook/zephyr-7b-sft-full

# Data training arguments
dataset_mixer:
  argilla/ultrafeedback-binarized-avg-rating-for-dpo: 1.0
dataset_splits:
- train
preprocessing_num_workers: 12

# DPOTrainer arguments
bf16: true
beta: 0.1
do_eval: true
evaluation_strategy: steps
eval_steps: 100
gradient_accumulation_steps: 1
gradient_checkpointing: true
learning_rate: 5.0e-7
log_level: info
logging_steps: 10
lr_scheduler_type: linear
max_length: 1024
max_prompt_length: 512
num_train_epochs: 3
optim: rmsprop
output_dir: data/notus-7b-dpo-full
per_device_train_batch_size: 8
per_device_eval_batch_size: 4
push_to_hub: true
hub_model_id: argilla/notus-7b-dpo-full
hub_private_repo: true
save_strategy: epoch
save_total_limit: 2 
seed: 42
warmup_ratio: 0.1
report_to:
  - wandb
  - tensorboard
